project:
  title: "Manuscript"
  output-dir: output

  render:
    - "manuscript.qmd"
    - "appendix.qmd"

format:
  html:
    toc: true
    include-in-header:
      - text: |
          <style type="text/css">
          h2.hide {
            display: none;
          }
          </style>
    language: 
      title-block-published: "Latest version"
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - html/custom.scss
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
